# Generated by Django 5.2.1 on 2025-05-29 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0002_alter_capsule_delivery_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='delivery_time',
            field=models.TimeField(default=datetime.time(0, 0), help_text='The scheduled time for the capsule to be delivered on the delivery_date.'),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='delivery_date',
            field=models.DateField(help_text='The scheduled date and time for the capsule to be delivered.'),
        ),
    ]
