# Generated by Django 5.2.1 on 2025-05-29 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0003_capsule_delivery_time_alter_capsule_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capsulecontent',
            name='thumbnail',
        ),
    ]
