# Generated by Django 5.2.1 on 2025-05-29 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0004_remove_capsulecontent_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='capsulerecipient',
            name='recipient_user',
            field=models.ForeignKey(blank=True, help_text='Optional: If the recipient is also a registered user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_capsules', to=settings.AUTH_USER_MODEL),
        ),
    ]
