# Generated by Django 5.2.1 on 2025-05-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0005_capsulerecipient_recipient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverylog',
            name='external_id',
        ),
        migrations.AddField(
            model_name='deliverylog',
            name='details',
            field=models.TextField(blank=True, help_text='Additional details about the delivery attempt, such as success messages or logs.', null=True),
        ),
    ]
