# Generated by Django 5.2.1 on 2025-05-30 16:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0006_remove_deliverylog_external_id_deliverylog_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='is_unlocked',
            field=models.BooleanField(default=False, help_text='Indicates if the capsule has been unlocked by the owner or recipient.'),
        ),
        migrations.AddField(
            model_name='capsulerecipient',
            name='access_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text="Unique token for unauthenticated access to this recipient's view of the capsule.", null=True, unique=True),
        ),
        migrations.AddField(
            model_name='capsulerecipient',
            name='token_generated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the access token was generated or last refreshed.', null=True),
        ),
    ]
