# Generated by Django 5.2.1 on 2025-05-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0007_capsule_is_unlocked_capsulerecipient_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsulerecipient',
            name='token_generated_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the access token was generated or last refreshed.', null=True),
        ),
    ]
