# Generated by Django 5.2.1 on 2025-05-31 18:11

import capsules.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0009_alter_capsulecontent_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsulecontent',
            name='file',
            field=models.FileField(blank=True, help_text="File content for 'image', 'video', 'audio', 'document' types. Null for text content.", null=True, upload_to=capsules.models.user_capsule_content_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', '.bmp', '.tiff', 'mp4', 'avi', 'mov', 'webm', '.mkv', '.flv', '.wmv', 'mp3', 'wav', 'ogg', 'm4a', '.flac', '.aac', '.wma', 'pdf', 'doc', 'docx', 'txt', 'rtf', '.odt', '.epub'])]),
        ),
    ]
