# Generated by Django 5.2.1 on 2025-06-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0011_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('capsule_created', 'Capsule Created'), ('delivery_success', 'Capsule Delivered'), ('delivery_fail', 'Capsule Delivery Failed'), ('new_shared_capsule', 'New Shared Capsule'), ('capsule_opened', 'Capsule Opened'), ('reminder', 'Reminder'), ('system_alert', 'System Alert'), ('transfer_notification', 'Capsule Transferred')], help_text='Categorizes the type of notification.', max_length=50),
        ),
    ]
