# Generated by Django 5.2.1 on 2025-06-21 15:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0012_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The exact date and time the capsule was created.'),
        ),
    ]
