# Generated by Django 5.2.1 on 2025-06-22 15:32

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0013_alter_capsule_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsulecontent',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, help_text="File content for 'image', 'video', 'audio', 'document' types. Null for text content.", max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'tiff', 'mp4', 'avi', 'mov', 'webm', 'mkv', 'flv', 'wmv', 'mp3', 'wav', 'ogg', 'm4a', 'flac', 'aac', 'wma', 'pdf', 'doc', 'docx', 'txt', 'rtf', 'odt', 'epub'])], verbose_name='file'),
        ),
    ]
